name: SonarQube Scan

on:
  pull_request:
    branches: [MiniSplit]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli-*.zip
          ./sonar-scanner-*/bin/sonar-scanner \
            -Dsonar.projectKey=com.bosch.eng2cloudsonar.bccsonar \
            -Dsonar.projectName=BCC_Project_sprint18 \
            -Dsonar.projectVersion=0.1 \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarqube.dev.bosch.com \
            -Dsonar.login=${SONAR_TOKEN}
